name: aventuras_jack_integradora
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.2.2
  shared_preferences: ^2.0.10
  # googleapis: ^0.60.5
  # googleapis_auth: ^0.3.11
  # googleapis_people: ^0.4.0
  # cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    # - assets/1.png
    # - assets/2.png
    # - assets/3.png
    # - assets/poster.jpg
    - assets/logoEmpresa.png
    - assets/icono.png
    - assets/facebook.png
    - assets/github.png
    - assets/google.png
    - assets/fondo.jpg
    - assets/icono2.png
    - assets/icono3.png
  fonts:
    - family: MiFuente
      fonts:
        - asset: assets/mifuente.ttf